# Generated by Django 4.0 on 2021-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakingNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
