"""
Django settings for NewsPortal project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3_u(!4vmlh05u1(@_$*x-!(kyhrm#at7x&+37jh$87599s-l=x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'fpages',
    'BreakingNews',
    'accounts',
    'sign',
    'protect',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'appointment',
    'django_apscheduler',

]

SITE_ID = 1

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

APSCHEDULER_RUN_NOW_TIMEOUT = 25

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'NewsPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPortal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = '465'
EMAIL_HOST_USER = 'ManAndEvg'
EMAIL_HOST_PASSWORD = 'QiwiPortal'
EMAIL_USE_SSL = True

ADMINS = [
    ('Victor', 'culolok@mail.ru'),
    # список всех админов в формате ('имя', 'их почта')
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_FORMS = {'signup': 'sign.models.CommonSignupForm'}

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SERVER_EMAIL = 'ManAndEvg@yandex.ru'

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'loggers': {
            'django': {
                'handlers': ['console', 'IO'],
                'level': 'DEBUG'
            },
            'django.request': {
                'handlers': ['ERCR'],
                'level': 'ERROR'
            },
            'django.server': {
                'handlers': ['ERCR'],
                'level': 'ERROR'
            },
            'django.template': {
                'handlers': ['ERCR'],
                'level': 'ERROR'
            },
            'django.db_backends': {
                'handlers': ['ERCR'],
                'level': 'ERROR'
            },
            'django.security': {
                'handlers': ['SC'],
                'level': 'INFO'
            }
        },
        'formatters': {
            'FERCR': {
                'format': '{asctime} {levelname} {message} {pathname} {sys.exc_info}',
                'style': '{',
            },
            'FSC': {
                'format': '{asctime} {levelname} {module} {message}',
                'style': '{',
            },
            'FIO': {
                'format': '{asctime} {levelname} {module} {message}',
                'style': '{',
            }
        },
        'filters': {
            'require_debug_true': {
                '()': 'django.utils.log.RequireDebugTrue',
            },

            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse',
                                        }

                    },
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'filters': ['require_debug_true'],
                'class': 'logging.StreamHandler',
            },
            'IO': {
                'level': 'INFO',
                'filters': ['require_debug_true'],
                'class': 'logging.FileHandler',
                'formatter': 'FIO',
                'filename': 'NewsPortal/general.log',
            },
            'ERCR': {
                'level': 'ERROR',
                'filters': ['require_debug_true'],
                'class': 'logging.FileHandler',
                'formatter': 'FERCR',
                'filename': 'NewsPortal/error.log',
            },
            'SC': {
                'level': 'INFO',
                'filters': ['require_debug_true'],
                'class': 'logging.FileHandler',
                'formatter': 'FSC',
                'filename': 'NewsPortal/security.log',
            },
            'mail_admins': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': ['django.utils.log.AdminEmailHandler', 'logging.FileHandler'],
                'filename': 'NewsPortal/general.log',
                    },
            }
        }
